apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dk5kxqhmu-java-quarkus 
  janus-idp.io/tekton: dk5kxqhmu-java-quarkus
  backstage.io/kubernetes-id: dk5kxqhmu-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dk5kxqhmu-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml